services:
  - type: web
    name: openpos-api
    runtime: node
    plan: free
    region: oregon
    buildCommand: corepack enable && pnpm install --frozen-lockfile && cd packages/database && npx prisma generate && npx prisma migrate deploy
    startCommand: cd apps/api && npx tsx src/main.ts
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.ytanvpjxqfdxcvghmzny:hyy-JfC-g2L-s6j@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres
      - key: JWT_SECRET
        value: openpos-mn7k2x9p4r8t1w5q3j6y0b8n2m4vc9
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: ADMIN_URL
        value: https://openpos-terminal.vercel.app
      - key: POS_URL
        value: https://openpos-terminal.vercel.app
      - key: KITCHEN_URL
        value: https://openpos-terminal.vercel.app
      - key: CUSTOMER_DISPLAY_URL
        value: https://openpos-terminal.vercel.app
    healthCheckPath: /health
